trigger:
- master

schedules:
- cron: '0 12 * * 0'
  displayName: WMI - master branch weekly Sunday build
  branches:
    include:
      - master
  always: true

jobs:
- template: .pipelines/build.yaml
- template: .pipelines/static.yaml
